def help(_role):
    # mengeluarkan list command berdasarkan _role
    if _role == "admin": # fungsi yg hanya bisa diakses admin
        print()
        print()
        print("===============================================  HELP  ==============================================")
        print()
        print("1. register              - Untuk melakukan registrasi user baru")
        print("2. login                 - Untuk melakukan login ke dalam sistem")
        print("3. add game              - Untuk menambah game yang dijual pada toko")
        print("4. store                 - Untuk melihat list game yang dijual pada toko")
        print("5. update game           - Untuk mengubah informasi game dengan informasi baru")
        print("6. update stock          - Untuk mengubah stok sebuah game pada toko")
        print("7. store search          - Untuk mendapatkan informasi game yang ada di toko")
        print("8. topup                 - Untuk menambahkan saldo kepada user")
        print("9. help                  - Untuk memberikan panduan penggunaan sistem")
        print("10. save                 - Untuk melakukan penyimpanan data ke dalam file setelah dilakukan perubahan")
        print("11. exit                 - Untuk keluar dari aplikasi")
        print("12. magic conch          - Panggil customer service")
        print("13. tic tac toe          - Apabila Anda bosan dan ingin bermain tic-tac-toe sendirian")

    else: # fungsi yang hanya bisa diakses user
        # _role == "user"
        print()
        print()
        print("================================================ HELP ===============================================")
        print()
        print("1. login                 - Untuk melakukan login ke dalam sistem")
        print("2. store                 - Untuk melihat list game yang dijual pada toko")
        print("3. buy game              - Untuk membeli game")
        print("4. list game             - Untuk melihat daftar game yang dimiliki pengguna")
        print("5. search my game        - Untuk mendapatkan informasi game pada inventory")
        print("6. store search          - Untuk mendapatkan informasi game yang ada di toko")
        print("7. history               - Untuk melihat riwayat pembelian game")
        print("8. help                  - Untuk memberikan panduan penggunaan sistem")
        print("9. save                  - Untuk melakukan penyimpanan data ke dalam file setelah dilakukan perubahan")
        print("10. exit                 - Untuk keluar dari aplikasi")
        print("11. magic conch          - Bertanya kepada customer service kami")
        print("12. tic tac toe          - Apabila Anda bosan dan ingin bermain tic-tac-toe sendirian")
